---
title: "New book is out"
author: "Michaël Aklin"
date: 2018-11-08T00:00:00
tags: ["Book", "Energy", "Energy poverty"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

Our book _Escaping the Energy Poverty Trap_ (MIT Press), co-authored with Patrick Bayer, S.P. Harish, and Johannes Urpelainen, is now available in bookstores (MIT has links to several sellers; [see here](https://mitpress.mit.edu/books/escaping-energy-poverty-trap)). 

Here's the blurb:

> The first comprehensive political science account of energy poverty, arguing that governments can improve energy access for their citizens through appropriate policy design.

> In today's industrialized world, almost everything we do consumes energy. While industrialized countries enjoy all the amenities of modern energy, more than a billion people in the developing world still lack energy access. Why is energy poverty persistent in some countries and not in others? Offering the first comprehensive political science account of energy poverty, Escaping the Energy Poverty Trap explores why governments have or have not been able to lead in providing modern energy to their least advantaged citizens.

> Focusing on access to modern cooking fuels and household electrification, the authors develop a new political-economic theory that introduces government interest, institutional capacity, and local accountability as key determinants of energy access. They draw on case studies from India, East Asia, Africa, and Latin America to offer the optimistic conclusion that governments can improve institutional capacity and local accountability through appropriate policy design. Energy poverty is a policy problem, the authors assert, and engaging with it as such offers new opportunities not only for ensuring equal energy access, but also for political, economic, and environmental development.

