---
title: "New paper in Nature Sustainability"
author: "Michaël Aklin"
date: 2020-01-07T00:00:00
tags: ["Energy", "Energy poverty", "Gender"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

_Nature Sustainability_ recently published our article on energy access and gender inequality (co-authored by Meital Rosenberg, Daniel Armanios, Paulina Jaramillo, and I). The question is simple: once a household gets access to electricity, who benefits from it? Many studies in the past have shown that electricity access benefits women (for instance on the labor market). We show that things are not that straightforward when we examine its effect on households. Looking specifically at India, we find that men tend to be the primary beneficiaries of electricity: it is the appliances they use that are bought first. Household dynamics shape how the benefits of energy access are split!

The article is available [here](https://www.nature.com/articles/s41893-019-0447-3){target="_blank"}. The replication package is available at [Harvard Dataverse](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DRVBZY){target="_blank"}. Our article was discussed in several newspapers including [The Hindu](https://www.thehindu.com/sci-tech/electrification-in-indian-households-benefits-men-more-than-women-study/article30400757.ece), the [Times of India](https://energy.economictimes.indiatimes.com/news/power/men-benefit-more-than-women-from-electrification-in-india/72962655){target="_blank"}, [Business Standard](https://www.business-standard.com/article/pti-stories/electrification-in-indian-households-benefits-men-more-than-women-study-119122600264_1.html){target="_blank"}, and others.
