---
title: "New article in Global Environmental Politics"
author: "Michaël Aklin"
date: 2020-10-29T00:00:00
categories: ["News"]
tags: ["climate change", "carbon pricing"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

October 29, 2020

My [paper](https://www.mitpressjournals.org/doi/full/10.1162/glep_a_00578) with Matto Mildenberger, "Prisoners of the Wrong Dilemma: Why Distributive Conflict, Not Collective Action, Characterizes the Politics of Climate Change," is out at _Global Environmental Politics_. You can find an ungated pre-print [here](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3281045). 

Long story short: many argue that the main obstacle to effective climate policy is global free-riding. States are trapped in a prisoners' dilemma, and we should put our effort into creating the kind of environment in which cooperation can be sustained.

This has generally been asserted without evidence.

The problem is: when we looked for evidence, we couldn't find it. 

Instead, we show that distributive politics (who gains and loses from different policies, and how influential these actors are) explains much more why climate policy is often weak _and_ is consistent with data. Thus, we should spend more time looking at solutions to these kinds of conflicts (which often take place within countries) than try to come up with yet another way to solve the global free-riding problem. 

