---
title: "New paper in PNAS"
author: "Michaël Aklin"
date: 2020-04-08T00:00:00
categories: ["Climate change", "Climate policy", "Carbon pricing", "Cap-and-trade"]
tags: ["Climate change", "Climate policy", "Carbon pricing", "Cap-and-trade"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

Patrick Bayer and I published a paper in [[PNAS](https://www.pnas.org/content/early/2020/04/01/1918128117){target="_blank"}] (ungated) on the effectiveness of the European Union Emissions Trading Scheme (EU ETS). The EU ETS is one of the most ambitious attempts to put a price on carbon emissions. However, it has often been criticized as being too generous toward firms and therefore not having enough 'bite.' People often point at the ETS' low permit prices as evidence for this. What we show is that (a) looking at prices is not particularly insightful (low prices are compatible with both an ineffective _and_ an effective ETS!), and (b) once we think in terms of counterfactual (what would emissions have looked like without the ETS), we find that it has actually been quite effective. 

The paper's available in open access [[here](https://www.pnas.org/content/early/2020/04/01/1918128117){target="_blank"}]. The data can be accessed  
[[here](https://dataverse.harvard.edu/dataverse/eused){target="_blank"}]. And some news outlets have picked up the story, such as 
[[_Ars Technica_](https://arstechnica.com/science/2020/04/eu-carbon-trading-market-has-reduced-emissions-despite-low-carbon-prices/){target="_blank"}].
