baseurl = "https://michaelaklin.github.io/"
title = "Michaël Aklin"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = "UA-126200481-1"
enableRobotsTXT = true
copyright = " "

publishDir = "../michaelaklin.github.io"

# Main menu items
[menu]
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    title = "Publications"
    url = "/publications/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/post/"
    weight = -100
  [[menu.main]]
    identifier = "teaching"
    name = "Teaching"
    title = "Teaching"
    url = "/teaching/"
    weight = -90

# Configuration Features
[params]
  header_title = "Michaël Aklin"                 # Your header title
  header_subtitle = "Associate Professor, University of Pittsburgh" # Your header subtitle
  home_image = "/images/avatar.png"          # Path to header image starting from the static directory
  recent_posts = 5                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    href = "http://github.com/youruser"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = ""
  [[params.social]]
    fa_icon = "fab fa-twitter fa-1x"
    href = ""
  [[params.social]]
    fa_icon = "fas fa-at fa-1x"
    href = ""
